GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Authorization with JWT",
  "author": "Tom Hanks",
  "url": "http:/localhost:3003",
  "likes": 100
}
###
PUT http://localhost:3003/api/blogs/62cab87378566c1bb8887fb5
Content-Type: application/json

{
  "title": "whatever",
  "author": "Tom Hanks",
  "url": "http:/localhost:3000",
  "likes": -2,
  "__v": 0,
  "_id": "62cab87378566c1bb8887fb5"
}

###
DELETE http://localhost:3003/api/blogs/62cab87378566c1bb8887fb9
