GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username":"tonyS",
   "password":"tonyP",
   "name":"Tony Stark"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username":"tonyS",
   "name":"Tony Stark"
}
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
   "name":"Tony Stark",
   "password":"tonyP"
}